version: '3.7'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./html:/data/www"
      - "./images:/data/images"
      - "./dir:/data/dir"
      - "./nginx.conf:/etc/nginx/nginx.conf"